access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
server:
  servlet:
    context-path: ${CONTEXT_PATH}
spring:
  jpa:
    hibernate:
      ddl-auto: update
  port: 8080
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.springframework.security: INFO